name: Update Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:     # Allows manual runs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v2
        with:
          github_user_name: sahilchauhan0603
          svg_out_path: assets/github-snake.svg
      - uses: EndBug/add-and-commit@v9
        with:
          branch: main
          message: "Update snake animation"
